# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'settingswindow.ui'
##
## Created by: Qt User Interface Compiler version 6.5.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractButton, QApplication, QComboBox, QDialog,
    QDialogButtonBox, QGroupBox, QLabel, QPushButton,
    QSizePolicy, QSlider, QWidget)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        if not Dialog.objectName():
            Dialog.setObjectName(u"Dialog")
        Dialog.resize(450, 580)
        self.buttonBox = QDialogButtonBox(Dialog)
        self.buttonBox.setObjectName(u"buttonBox")
        self.buttonBox.setGeometry(QRect(0, 540, 440, 32))
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBox.sizePolicy().hasHeightForWidth())
        self.buttonBox.setSizePolicy(sizePolicy)
        self.buttonBox.setOrientation(Qt.Horizontal)
        self.buttonBox.setStandardButtons(QDialogButtonBox.Apply)
        self.groupBox_BigShifts = QGroupBox(Dialog)
        self.groupBox_BigShifts.setObjectName(u"groupBox_BigShifts")
        self.groupBox_BigShifts.setGeometry(QRect(10, 40, 431, 71))
        self.label_BigShifts_Advice = QLabel(self.groupBox_BigShifts)
        self.label_BigShifts_Advice.setObjectName(u"label_BigShifts_Advice")
        self.label_BigShifts_Advice.setGeometry(QRect(20, 24, 281, 16))
        self.horizontalSlider_BigShifts = QSlider(self.groupBox_BigShifts)
        self.horizontalSlider_BigShifts.setObjectName(u"horizontalSlider_BigShifts")
        self.horizontalSlider_BigShifts.setGeometry(QRect(20, 44, 372, 22))
        self.horizontalSlider_BigShifts.setMinimum(1)
        self.horizontalSlider_BigShifts.setMaximum(41)
        self.horizontalSlider_BigShifts.setOrientation(Qt.Horizontal)
        self.horizontalSlider_BigShifts.setTickPosition(QSlider.TicksBelow)
        self.horizontalSlider_BigShifts.setTickInterval(1)
        self.label_BigShifts = QLabel(self.groupBox_BigShifts)
        self.label_BigShifts.setObjectName(u"label_BigShifts")
        self.label_BigShifts.setGeometry(QRect(401, 40, 20, 20))
        self.label_BigShifts.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_Overlaps = QGroupBox(Dialog)
        self.groupBox_Overlaps.setObjectName(u"groupBox_Overlaps")
        self.groupBox_Overlaps.setGeometry(QRect(10, 300, 431, 171))
        self.label_overlap_MDX = QLabel(self.groupBox_Overlaps)
        self.label_overlap_MDX.setObjectName(u"label_overlap_MDX")
        self.label_overlap_MDX.setGeometry(QRect(401, 40, 20, 20))
        self.label_overlap_MDX.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.horizontalSlider_overlap_MDX = QSlider(self.groupBox_Overlaps)
        self.horizontalSlider_overlap_MDX.setObjectName(u"horizontalSlider_overlap_MDX")
        self.horizontalSlider_overlap_MDX.setGeometry(QRect(20, 44, 371, 22))
        self.horizontalSlider_overlap_MDX.setMinimum(0)
        self.horizontalSlider_overlap_MDX.setMaximum(20)
        self.horizontalSlider_overlap_MDX.setSingleStep(5)
        self.horizontalSlider_overlap_MDX.setValue(0)
        self.horizontalSlider_overlap_MDX.setOrientation(Qt.Horizontal)
        self.horizontalSlider_overlap_MDX.setInvertedAppearance(False)
        self.horizontalSlider_overlap_MDX.setTickPosition(QSlider.TicksBelow)
        self.horizontalSlider_overlap_MDX.setTickInterval(1)
        self.horizontalSlider_overlap_MDX.setProperty("inputConversionRatio", 0.050000000000000)
        self.horizontalSlider_overlap_MDXv3 = QSlider(self.groupBox_Overlaps)
        self.horizontalSlider_overlap_MDXv3.setObjectName(u"horizontalSlider_overlap_MDXv3")
        self.horizontalSlider_overlap_MDXv3.setGeometry(QRect(20, 94, 371, 22))
        self.horizontalSlider_overlap_MDXv3.setMinimum(2)
        self.horizontalSlider_overlap_MDXv3.setMaximum(40)
        self.horizontalSlider_overlap_MDXv3.setSingleStep(2)
        self.horizontalSlider_overlap_MDXv3.setValue(2)
        self.horizontalSlider_overlap_MDXv3.setSliderPosition(2)
        self.horizontalSlider_overlap_MDXv3.setOrientation(Qt.Horizontal)
        self.horizontalSlider_overlap_MDXv3.setTickPosition(QSlider.TicksBelow)
        self.horizontalSlider_overlap_MDXv3.setTickInterval(1)
        self.label_overlap_MDXv3 = QLabel(self.groupBox_Overlaps)
        self.label_overlap_MDXv3.setObjectName(u"label_overlap_MDXv3")
        self.label_overlap_MDXv3.setGeometry(QRect(400, 90, 20, 20))
        self.label_overlap_MDXv3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_5 = QLabel(self.groupBox_Overlaps)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 24, 281, 16))
        self.label_6 = QLabel(self.groupBox_Overlaps)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 74, 281, 16))
        self.label_7 = QLabel(self.groupBox_Overlaps)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 124, 281, 16))
        self.horizontalSlider_overlap_demucs = QSlider(self.groupBox_Overlaps)
        self.horizontalSlider_overlap_demucs.setObjectName(u"horizontalSlider_overlap_demucs")
        self.horizontalSlider_overlap_demucs.setGeometry(QRect(20, 144, 371, 22))
        self.horizontalSlider_overlap_demucs.setMinimum(0)
        self.horizontalSlider_overlap_demucs.setMaximum(20)
        self.horizontalSlider_overlap_demucs.setSingleStep(5)
        self.horizontalSlider_overlap_demucs.setValue(0)
        self.horizontalSlider_overlap_demucs.setOrientation(Qt.Horizontal)
        self.horizontalSlider_overlap_demucs.setTickPosition(QSlider.TicksBelow)
        self.horizontalSlider_overlap_demucs.setTickInterval(1)
        self.horizontalSlider_overlap_demucs.setProperty("inputConversionRatio", 0.050000000000000)
        self.label_overlap_demucs = QLabel(self.groupBox_Overlaps)
        self.label_overlap_demucs.setObjectName(u"label_overlap_demucs")
        self.label_overlap_demucs.setGeometry(QRect(400, 140, 20, 20))
        self.label_overlap_demucs.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox_Weights = QGroupBox(Dialog)
        self.groupBox_Weights.setObjectName(u"groupBox_Weights")
        self.groupBox_Weights.setGeometry(QRect(10, 120, 431, 171))
        self.label_weight_MDXv3 = QLabel(self.groupBox_Weights)
        self.label_weight_MDXv3.setObjectName(u"label_weight_MDXv3")
        self.label_weight_MDXv3.setGeometry(QRect(401, 40, 20, 20))
        self.label_weight_MDXv3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.horizontalSlider_weight_MDXv3 = QSlider(self.groupBox_Weights)
        self.horizontalSlider_weight_MDXv3.setObjectName(u"horizontalSlider_weight_MDXv3")
        self.horizontalSlider_weight_MDXv3.setGeometry(QRect(20, 44, 371, 22))
        self.horizontalSlider_weight_MDXv3.setMinimum(0)
        self.horizontalSlider_weight_MDXv3.setMaximum(10)
        self.horizontalSlider_weight_MDXv3.setValue(0)
        self.horizontalSlider_weight_MDXv3.setOrientation(Qt.Horizontal)
        self.horizontalSlider_weight_MDXv3.setTickPosition(QSlider.TicksBelow)
        self.horizontalSlider_weight_MDXv3.setTickInterval(1)
        self.horizontalSlider_weight_VOCFT = QSlider(self.groupBox_Weights)
        self.horizontalSlider_weight_VOCFT.setObjectName(u"horizontalSlider_weight_VOCFT")
        self.horizontalSlider_weight_VOCFT.setGeometry(QRect(20, 94, 371, 22))
        self.horizontalSlider_weight_VOCFT.setMinimum(0)
        self.horizontalSlider_weight_VOCFT.setMaximum(10)
        self.horizontalSlider_weight_VOCFT.setValue(0)
        self.horizontalSlider_weight_VOCFT.setOrientation(Qt.Horizontal)
        self.horizontalSlider_weight_VOCFT.setTickPosition(QSlider.TicksBelow)
        self.horizontalSlider_weight_VOCFT.setTickInterval(1)
        self.label_weight_VOCFT = QLabel(self.groupBox_Weights)
        self.label_weight_VOCFT.setObjectName(u"label_weight_VOCFT")
        self.label_weight_VOCFT.setGeometry(QRect(400, 90, 20, 20))
        self.label_weight_VOCFT.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.label_11 = QLabel(self.groupBox_Weights)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 24, 281, 16))
        self.label_12 = QLabel(self.groupBox_Weights)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 74, 281, 16))
        self.label_13 = QLabel(self.groupBox_Weights)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 124, 281, 16))
        self.horizontalSlider_weight_HQ3 = QSlider(self.groupBox_Weights)
        self.horizontalSlider_weight_HQ3.setObjectName(u"horizontalSlider_weight_HQ3")
        self.horizontalSlider_weight_HQ3.setGeometry(QRect(20, 144, 371, 22))
        self.horizontalSlider_weight_HQ3.setMinimum(0)
        self.horizontalSlider_weight_HQ3.setMaximum(10)
        self.horizontalSlider_weight_HQ3.setValue(0)
        self.horizontalSlider_weight_HQ3.setOrientation(Qt.Horizontal)
        self.horizontalSlider_weight_HQ3.setTickPosition(QSlider.TicksBelow)
        self.horizontalSlider_weight_HQ3.setTickInterval(1)
        self.label_weight_HQ3 = QLabel(self.groupBox_Weights)
        self.label_weight_HQ3.setObjectName(u"label_weight_HQ3")
        self.label_weight_HQ3.setGeometry(QRect(400, 140, 20, 20))
        self.label_weight_HQ3.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.groupBox = QGroupBox(Dialog)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 480, 431, 51))
        self.comboBox_OutputFormat = QComboBox(self.groupBox)
        self.comboBox_OutputFormat.addItem("")
        self.comboBox_OutputFormat.addItem("")
        self.comboBox_OutputFormat.setObjectName(u"comboBox_OutputFormat")
        self.comboBox_OutputFormat.setGeometry(QRect(10, 24, 411, 21))
        self.label_15 = QLabel(Dialog)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(10, 10, 431, 21))
        self.label_15.setAlignment(Qt.AlignCenter)
        self.button_ExportSettings = QPushButton(Dialog)
        self.button_ExportSettings.setObjectName(u"button_ExportSettings")
        self.button_ExportSettings.setGeometry(QRect(120, 540, 101, 31))
        self.button_ImportSettings = QPushButton(Dialog)
        self.button_ImportSettings.setObjectName(u"button_ImportSettings")
        self.button_ImportSettings.setGeometry(QRect(10, 540, 101, 31))
        self.button_RestoreDefaults = QPushButton(Dialog)
        self.button_RestoreDefaults.setObjectName(u"button_RestoreDefaults")
        self.button_RestoreDefaults.setGeometry(QRect(230, 540, 101, 31))

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)

        QMetaObject.connectSlotsByName(Dialog)
    # setupUi

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QCoreApplication.translate("Dialog", u"Advanced Settings", None))
        self.groupBox_BigShifts.setTitle(QCoreApplication.translate("Dialog", u"Bigshifts", None))
        self.label_BigShifts_Advice.setText(QCoreApplication.translate("Dialog", u"Set slider to 1 to disable that feature (default: 11)", None))
        self.label_BigShifts.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.groupBox_Overlaps.setTitle(QCoreApplication.translate("Dialog", u"Overlaps", None))
        self.label_overlap_MDX.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.label_overlap_MDXv3.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.label_5.setText(QCoreApplication.translate("Dialog", u"overlap_MDX: (default: 0)", None))
        self.label_6.setText(QCoreApplication.translate("Dialog", u"overlap_MDXv3: (default: 8)", None))
        self.label_7.setText(QCoreApplication.translate("Dialog", u"overlap_demucs: (default: 0.6)", None))
        self.label_overlap_demucs.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.groupBox_Weights.setTitle(QCoreApplication.translate("Dialog", u"Weights", None))
        self.label_weight_MDXv3.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.label_weight_VOCFT.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.label_11.setText(QCoreApplication.translate("Dialog", u"weight_MDXv3: (default: 6)", None))
        self.label_12.setText(QCoreApplication.translate("Dialog", u"weight_VOCFT: (default: 5)", None))
        self.label_13.setText(QCoreApplication.translate("Dialog", u"weight_HQ3: (default: 2)", None))
        self.label_weight_HQ3.setText(QCoreApplication.translate("Dialog", u"0", None))
        self.groupBox.setTitle(QCoreApplication.translate("Dialog", u"Output format", None))
        self.comboBox_OutputFormat.setItemText(0, QCoreApplication.translate("Dialog", u"PCM_16", None))
        self.comboBox_OutputFormat.setItemText(1, QCoreApplication.translate("Dialog", u"FLOAT", None))

        self.label_15.setText(QCoreApplication.translate("Dialog", u"<html><head/><body><p><span style=\" font-weight:600; color:#ff0000;\">Proceed only if you know what you are doing!\u00a0</span> Default values are good enough.</p></body></html>", None))
#if QT_CONFIG(statustip)
        self.button_ExportSettings.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_ExportSettings.setText(QCoreApplication.translate("Dialog", u"Export settings", None))
#if QT_CONFIG(statustip)
        self.button_ImportSettings.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_ImportSettings.setText(QCoreApplication.translate("Dialog", u"Import settings", None))
#if QT_CONFIG(statustip)
        self.button_RestoreDefaults.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_RestoreDefaults.setText(QCoreApplication.translate("Dialog", u"Restore defaults", None))
    # retranslateUi

